### ISSUE TITLE
misplaced div on the timers page

### ISSUE THREAD

**Issue by tusharnankani** [DevelopersLeague/EverHustle-FrontEnd#4]
![image](https://user-images.githubusercontent.com/61280281/117877604-643c3900-b2c2-11eb-96c6-1b30eebae5d9.png)

New timer is misplaced on the top left corner.

**Comment by ShyrenMore** [comment]
Thank you for letting us know, we'll be working on this issue soon

**Comment by ShyrenMore** [comment]
ba5c7c52dc9faee9d5a67c01d8553d5a8685fb23
