### ISSUE TITLE
user already logged in on the deployed website

### ISSUE THREAD

**Issue by tusharnankani** [DevelopersLeague/EverHustle-FrontEnd#7]
When I opened the link the user was already logged in.

![image](https://user-images.githubusercontent.com/61280281/119880646-16723280-bf4a-11eb-8c07-ba232bafe76d.png)

When I checked the credentials were: `testuseraniket@gmail.com` and `password123`; and I never created one before.

![image](https://user-images.githubusercontent.com/61280281/119880778-37d31e80-bf4a-11eb-9e74-2635b2a2b868.png)

**Comment by ShyrenMore** [comment]
Thanks for letting us know about this, will investigate this in the next few weeks.
